name: Nuget

on:
  push:
    tags: 'v*.*.*'

jobs:
  pack:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Determine version
      run: echo "::set-env name=VERSION::$(git describe --tags --dirty)"
    - name: Show version
      run: echo 'Version: ${VERSION:1}
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=${VERSION:1}
    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
    - name: Publish to github
      run: dotnet nuget push './artifacts/MailerQ.${VERSION:1}.nupkg' --source 'github'
